

<nav class="admin-nav">
    <a href="/vino-mornag/index.php"><button>Home</button></a>
    <button id='commandes-list' class="commandes-list"><a href="../../controllers/admin/adminCommandes.php">Orders List</a> </button>
    <button class=""><a href="adminPannel.php">Product List</a></button>
    <button id="add-product-button">Add Product</button>
    <form action="../../libraries/sessionDestroy.php">
        <button type="submit">Logout</button>
    </form>
</nav>