
<div class="hero-video">

    <div class="hero-title">
        <span>Welcome to santa mornag</span>
        <h1>Vino mornag</h1>
        <span id="winery">winery</span>
    </div>  
    
    <video src="video/hero.mp4" autoplay="" loop="" muted="" preload="" playsinline=""></video>   
</div>

<div class="home-intro">

    <div class="visit">

        <div class="visit-wrapper">
            <span>Plan you central coast</span>
            <h2>visit</h2>
            <h3>Santa Mornag Ranch AVA</h3>
            <p>Taste limited releases, enjoy a bite and kick back at our tasting room and café in the historic town of Santa Mornag</p>
            <a href="Learn more"></a>
        </div>
        
    </div>

    <div class="visit-img">
        
    </div>
</div>

<div class="home-shop">
    <div class="title-home-shop">
        <span>Explore our win</span>
        <h2>shop</h2>
        <a id="see-more-btn" href="controllers/products/products.php">See all wines</a>
    </div>
</div>

<div class="land">
    <div class="land-content">
        <span>THE BACKBONE OF OUR WINE</span>
        <h2>land</h2>
        <p>Our estate Mornag Vineyard stands alone and apart as the only vineyard in the Santa Mornag Ranch AVA of Paso Robles.</p>
        <a id="see-more-btn" href="#">Learn more</a>
    </div>
</div>