<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vino</title>

    <!-- Css link-->
    <link rel="stylesheet" href = <?= Path::root() . "css/style.css" ?> >

    <!-- font awesome cdn-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>

<header>
    <div class="logo-cart">
        <a href="/vino-mornag/index.php"><img src= <?= Path::imagePath() ."logoblanc1.png" ?> alt="logo"></a>
    </div>

    <nav class="cart-nav">
        <ul>
            <a href="/vino-mornag/index.php">
                <li>Home</li>
            </a>
            <a href= <?= Path::controllers() . "products/products.php"?>>
                <li>Shop</li>
            </a>
            <a href="">
                <li>About us</li>
            </a>
        </ul>
    </nav>
</header>

<body class="sc5">
    <div style="margin-top:2%;font-size:20px;" class="success hide payment-success">
        <p>Payement success</p>
    </div>

    <div class="modal-wrapper hide">
        <div class="modal clearfix">
            <div class="modal-product">

                <div class="round-shape"></div>
            </div>
            <div class="modal-info">
                <div class="info">
                    <h2>Payment Information</h2>
                    <form action="#">
                        <ul class="form-list">
                            <li class="form-list-row">
                                <div class="user">
                                    <label for="#">First Name</label><br>
                                    <i class="fas fa-user"></i></i><input id="firstNameInput" name="firstName" type="text" required>
                                    <p id="first-name-warning" class="warning hide">First name is invalid</p>
                                </div>

                            </li>
                            <li class="form-list-row">
                                <div class="user">
                                    <label for="#">Last Name</label><br>
                                    <i class="fas fa-user"></i></i><input id="lastNameInput" name="lastName" type="text" required>
                                    <p id="last-name-warning" class="warning hide">Last name is invalid</p>
                                </div>
                            </li>
                            <li class="form-list-row">
                                <div class="user">
                                    <label for="#">Email</label><br>
                                    <i class="fa fa-envelope"></i></i><input id="emailInput" name="email"  required>
                                    <p id="email-warning" class="warning hide">Email is invalid</p>
                                </div>
                            </li>
                            <li class="form-list-row">
                                <div class="number">
                                    <label for="#">Card Number</label><br>
                                    <i class="far fa-credit-card"></i><input type="text" required>
                                </div>

                            </li>
                            <li class="form-list-row clearfix">
                                <div class="date">
                                    <label for="#">Expiration Date</label><br>
                                    <input class="month" type="text" required placeholder="MM">
                                    <input class="year" type="text" required placeholder="YY">
                                </div>
                                <div class="cvc">
                                    <label for="#">CVC</label><i class="fas fa-question-circle"></i><br>
                                    <input type="text" required placeholder="123">
                                </div>
                            </li>
                        </ul>
                        <button class="pay-btn">Pay Now</button>

                    </form>
                    <button class="back-cart">Back to cart</button>
                </div>
            </div>
        </div>
    </div>

    <main id='cart-main'>


    </main>


    <footer class="cart-footer">
        <p>© Copyright 2021 Santa Mornag Winery</p>
        <p>Winery Ecommerce by Ahmed ben saber</p>
    </footer>

<!-- jquery cdn-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- basket class -->
<script src= <?= Path::root() . 'js/classes/Basket.class.js'?>></script>

<!-- orderform class js -->
<script src= <?= Path::root() . 'js/classes/OrderForm.class.js'?>></script>

<!-- modal class js -->
<script src= <?= Path::root() . 'js/classes/Modal.class.js'?>></script>

<!-- Edit modal class js-->
<script src= <?= Path::root() . 'js/classes/EditProductModal.class.js'?>></script>

<!-- Add modal class js-->
<script src= <?= Path::root() . 'js/classes/AddProductModal.class.js'?>></script>

<!-- Checkout modal class js-->
<script src= <?= Path::root() .'js/classes/CheckoutModal.class.js'?>></script>

<!-- Checkout modal class js-->
<script src= <?= Path::root() . 'js/classes/OrderAdmin.class.js'?>></script>

<!-- Search bar class js-->
<script src= <?= Path::root() . 'js/classes/SearchBar.class.js'?>></script>


<!-- javascript link-->
<script src= <?= Path::root() . "js/main.js"?> defer></script>



</body>

</html>