<div class="hero-products">
    <div class="hero-product-content">
        <span>wine</span>
        <h1>shop</h1>
        <p>Browse our estate-grown wines and taste what the Wine Advocate called “keenly priced, high-quality wines that deserve to be better known.”</p>
    </div>
</div>

<div class="search-bar">
    
    <div class="search-bar-container">
      <input id="search-product-input" type="text" placeholder="Search...">
      <div class="search"></div>
    </div>
    

    <div class="container">
  
    <div class="range-slider">
      <span id="rs-bullet" class="rs-label">0</span>
      <input id="rs-range-line" class="rs-range" type="range" value="0" min="0" max="200">
      
    </div>
    
    <div class="box-minmax">
      <span>0</span><span>200</span>
    </div>
  
</div>

</div>


<div class="product-container">

<?php if(!empty($products)) :?>
    
    <?php foreach($products as $product):?>
        <div class="product">
    
            <div class="product-wrapper">
                
                <div class="product-content">
    
                    <span><?= $product["year"]?></span>
                    <p class="name"><?= $product["ProductName"]?></p>
                    <p class="price"><?= $product["Price"]?> $</p>
                    <a class="product-details-btn" href=  "productDetails.php?id=<?= $product['Id']?>">More details</a>
                </div>
                
            </div>
                
                <img src="<?= Path::imagePath() . "products/" . $product['Picture']?>" alt="vin">
    
        </div>
        <?php endforeach;?>
    
        <?php else :?>
            <h2>No products found</h2>
        <?php endif;?>
    

</div>